### ISSUE TITLE
facepalm connectivity

### ISSUE THREAD

**Issue by donsizemore** [DICE-UNC/DE#11]
stderr": "\nA connection to the database could not be established.  Please verify that the\nconnection settings and credentials are correct.\n\nHost: <<FQDN>>\nPort: 5432\nDatabase: <<DB>>\nUser: postgres"

.pgpass entries work. CLI/manual connectivity works. added docker address range to pg_hba.conf. still can't hook up facepalm-within-docker to bare-metal postgresql. still poking.

**Comment by michael-conway** [comment]
I think running facepalm in docker is completely unnecessary

Let's run it from the cmd line tomorrow

**Comment by donsizemore** [comment]
built facepalm-standalone.jar. closing.
